name: wallet_connect_scanner_demo
description: QR Code Scanner for WalletConnect
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  build_runner: ^2.4.6
  envied: ^0.3.0+3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_gen_runner: ^5.3.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  permission_handler: ^10.4.3
  scan: ^1.6.0
  wallet_connect_repository:
    path: ./packages/wallet_connect_repository
  wallet_connect_scanner_ui:
    path: ./packages/wallet_connect_scanner_ui

dev_dependencies:
  bloc_test: ^9.1.2
  envied_generator: ^0.3.0+3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
